# -*- coding: utf-8 -*-
"""streamlit_trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNAn-46KCM1vfmYnEvoslSw3Gb-FWdxb
"""

!pip install streamlit

import streamlit as st

st.set_page_config(page_title="life of PS", page_icon="📝", layout="centered")
st.title("Short description of my life")
st.header("Hello I'm Prasanna")
st.write("I'm a DataScientist plus musi teacher")

!curl ipv4.icanhazip.com

!npx localtunnel --port 8501

